version: '3.7'
services:
  bff:
    build:
      context: .
      dockerfile: bff/Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy  # Ensures RabbitMQ is ready
      mongodb_container:
        condition: service_started
    environment:
      - ENVIRONMENT=docker
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/  # Kombu connection URL
    env_file:
      - ./env.docker

  ai-nlp-llm:
    build:
      context: .
      dockerfile: ai-nlp-llm/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb_container:
        condition: service_started
    environment:
      - ENVIRONMENT=docker
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - ./env.docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 60s
      retries: 3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP messaging port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      retries: 5

  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    ports:
      - "27018:27017"
