services:


  bff:
    build:
      context: ..
      dockerfile: ./backendServices/bff/Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb_container:
        condition: service_started
    networks:
      - bible_net
    environment:
      - ENVIRONMENT=docker
      - SERVICE_NAME=BFF_Service
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/  # Kombu connection URL
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/mydatabase
    env_file:
      - ../env.docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      retries: 3

  ml_service:
    build:
      context: ..
      dockerfile: ./backendServices/ml_service/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb_container:
        condition: service_started
    environment:
      - ENVIRONMENT=docker
      - SERVICE_NAME=ML_Service
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    env_file:
      - ../env.docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 60s
      retries: 3
    networks:
      - bible_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP messaging port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      retries: 5
    networks:
      - bible_net

  log_service:
    build:
      context: ..
      dockerfile: ./backendServices/log_service/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb_container:
        condition: service_started
    environment:
      - ENVIRONMENT=docker
    ports:
      - "5555:5555"
    env_file:
      - ../env.docker
    networks:
      - bible_net
    healthcheck:
      test: [ "CMD-SHELL", "echo 'ok'" ]
      interval: 30s
      timeout: 5s
      retries: 3

  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    ports:
      - "27018:27017"
    networks:
      - bible_net

  sql_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # <- bind mount
      - prometheus_data:/prometheus                                  # <- keep named volume only for data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      log_service:
        condition: service_healthy
    networks:
      - bible_net

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml:ro
    tmpfs:
      - /var/loki
    networks:
      - bible_net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - bible_net

networks:
  bible_net:
    driver: bridge



volumes:
  prometheus_data:
  postgres_data:
